"""Add user_id to Pin

Revision ID: 2a5786f5e30c
Revises: 378b9ac1f411
Create Date: 2025-05-26 12:07:00.457153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a5786f5e30c'
down_revision: Union[str, None] = '378b9ac1f411'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pin', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('pin', sa.Column('type', sa.String(length=50), nullable=True))
    op.add_column('pin', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('pin', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'pin', 'user', ['user_id'], ['id'])
    op.drop_column('pin', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pin', sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pin', type_='foreignkey')
    op.drop_column('pin', 'created_at')
    op.drop_column('pin', 'date')
    op.drop_column('pin', 'type')
    op.drop_column('pin', 'user_id')
    # ### end Alembic commands ###
